# Numerical Computing with Python and Numpy

In [2]:
# !pip install numpy --upgrade --quiet

`yield_of_apples = w1 * temperature + w2 * rainfall + w3 * humidity`
We're expressing the yield of apples as a weighted sum of the temperature, rainfall and humidity. Obviously, this is an approximation, since the actual relation may not necessarily be linear. But a simple linear model like this often works well in practice.

Based on some statical analysis of historical data, we might we able to come up with reasonable values for the weights `w1`, `w2` and `w3`. Here's an example set of values:

In [4]:
w1, w2, w3 = 0.3, 0.2, 0.5

Given some climate data for a region, we can now predict what the yield of apples in the region might look like. Here's some sample data:
``` 
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]
```
To begin, we can define some variables to record the climate data for a region.

In [5]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [6]:
weights = [w1, w2, w3]

In [12]:
def crop_yeilds(region, weights): 
    result = 0
    for x, w in zip(region, weights): 
        result += x * w
    return result

In [15]:
kanto_yield_apples = crop_yeilds(kanto, weights)

In [16]:
print("The expected yield of apples in Kanto region is {} tons per hectare.".format(kanto_yield_apples))

The expected yield of apples in Kanto region is 56.8 tons per hectare.


## Going from Python lists to Numpy arrays

The Numpy library provides a built-in function to perform the dot product of two vectors. However, the lists must first be converted to numpy arrays before we can perform the operation. To begin, let's import the `numpy` module. It is common practice to import numpy with the alias `np`.

In [17]:
import numpy as np

Numpy arrays can be created using the `np.array` function.

In [18]:
kanto = np.array([73,67,43])

In [19]:
kanto

array([73, 67, 43])

In [20]:
weights = np.array([0.3,0.2,0.5])

In [21]:
weights

array([0.3, 0.2, 0.5])

In [22]:
type(kanto)

numpy.ndarray

In [23]:
type(weights)

numpy.ndarray

Just like lists, Numpy arrays support the indexing notation `[]`

In [25]:
print(weights[1])

0.2


## Operating on Numpy arrays

We can now compute the dot product of the two vectors using the `np.dot` function

In [27]:
print(np.dot(kanto, weights))

56.8


We can achieve the same result with lower level operations supported by Numpy arrays: performing an element-wise multiplication and calculating the sum of the resulting numbers.

In [28]:
(kanto * weights).sum()

np.float64(56.8)

The `*` operator performs an element-wise multiplication of two arrays (assuming they have the same size), and the `sum` method calcuates the sum of numbers in an array.

## Benefits of using Numpy arrays

There are a couple of important benefits of using Numpy arrays instead of Python lists for operating on numerical data:

- **Ease of use**: You can write small, concise and intutive mathematical expressions like `(kanto * weights).sum()` rather than using loops & custom functions like `crop_yeild`.
- **Performance**: Numpy operations and functions are implemented internally in C++, which makes them much faster than using Python statements & loops which are interpreted at runtime

Here's a quick comparision of dot products done of vectors with a million elements each using Python loops vs. Numpy arrays.

In [31]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [32]:
arr1 * arr2

array([ 4, 10, 18])

In [33]:
arr2.sum()

np.int64(15)

In [34]:
arr1 = list(range(1000000))
arr2 = list(range(1000000,2000000))

arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [35]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1 * x2
print(result)

833332333333500000
CPU times: total: 531 ms
Wall time: 547 ms


In [36]:
%%time
print(np.dot(arr1_np, arr2_np))

833332333333500000
CPU times: total: 0 ns
Wall time: 3.8 ms


As you can see, using `np.dot` is 100 times faster than using a `for` loop. This makes Numpy especially useful while working with really large datasets with tens of thousands or millions of data points.

Let's save our work before continuing.

## Multi-dimensional Numpy arrays 

We can now go one step further, and represent the climate data for all the regions together using a single 2-dimensional Numpy array.

In [57]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64], 
                         [87, 134, 58],
                         [102, 43, 37], 
                         [69, 96, 70]])

In [58]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [59]:
climate_data.shape

(5, 3)

In [60]:
weights

array([0.3, 0.2, 0.5])

In [61]:
weights.shape

(3,)

Same output for below three different inputs, how `.dot()` , `.matlmul()` and `@` works

In [62]:
np.dot(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [63]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [64]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

### Example array

In [70]:
# 1D array
arr1 = np.array([[1,2,3]])
print(x)
print(x.shape)

[[1 2 3]]
(1, 3)


In [71]:
# 2D array 
arr2 = np.array([[1,2,3], 
                [4,5,6]])
print(arr2) 
print(arr2.shape) 

[[1 2 3]
 [4 5 6]]
(2, 3)


In [72]:
# 3D array
arr3 = np.array([
    [[1,2,3], 
     [4,5,6]],
    [[1,2,3], 
     [4,5,6]]
])
print(arr3) 
print(arr3.shape) 

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)


All the elements in a numpy array have the same datatype. You can check the data type of an array using the `.dtype` property

In [74]:
arr1.dtype

dtype('int64')

If an array contains even a single floating point number, all the other elements are also coverted to floats.

In [75]:
weights.dtype

dtype('float64')

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

y = np.array([[[1],[2]],
              [[3],[4]]])

y.shape