# Numerical Computing with Python and Numpy

In [2]:
# !pip install numpy --upgrade --quiet

`yield_of_apples = w1 * temperature + w2 * rainfall + w3 * humidity`
We're expressing the yield of apples as a weighted sum of the temperature, rainfall and humidity. Obviously, this is an approximation, since the actual relation may not necessarily be linear. But a simple linear model like this often works well in practice.

Based on some statical analysis of historical data, we might we able to come up with reasonable values for the weights `w1`, `w2` and `w3`. Here's an example set of values:

In [4]:
w1, w2, w3 = 0.3, 0.2, 0.5

Given some climate data for a region, we can now predict what the yield of apples in the region might look like. Here's some sample data:
``` 
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]
```
To begin, we can define some variables to record the climate data for a region.

In [5]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [6]:
weights = [w1, w2, w3]

In [12]:
def crop_yeilds(region, weights): 
    result = 0
    for x, w in zip(region, weights): 
        result += x * w
    return result

In [15]:
kanto_yield_apples = crop_yeilds(kanto, weights)

In [16]:
print("The expected yield of apples in Kanto region is {} tons per hectare.".format(kanto_yield_apples))

The expected yield of apples in Kanto region is 56.8 tons per hectare.


## Going from Python lists to Numpy arrays

The Numpy library provides a built-in function to perform the dot product of two vectors. However, the lists must first be converted to numpy arrays before we can perform the operation. To begin, let's import the `numpy` module. It is common practice to import numpy with the alias `np`.

In [1]:
import numpy as np

Numpy arrays can be created using the `np.array` function.

In [18]:
kanto = np.array([73,67,43])

In [19]:
kanto

array([73, 67, 43])

In [20]:
weights = np.array([0.3,0.2,0.5])

In [21]:
weights

array([0.3, 0.2, 0.5])

In [22]:
type(kanto)

numpy.ndarray

In [23]:
type(weights)

numpy.ndarray

Just like lists, Numpy arrays support the indexing notation `[]`

In [25]:
print(weights[1])

0.2


## Operating on Numpy arrays

We can now compute the dot product of the two vectors using the `np.dot` function

In [27]:
print(np.dot(kanto, weights))

56.8


We can achieve the same result with lower level operations supported by Numpy arrays: performing an element-wise multiplication and calculating the sum of the resulting numbers.

In [28]:
(kanto * weights).sum()

np.float64(56.8)

The `*` operator performs an element-wise multiplication of two arrays (assuming they have the same size), and the `sum` method calcuates the sum of numbers in an array.

## Benefits of using Numpy arrays

There are a couple of important benefits of using Numpy arrays instead of Python lists for operating on numerical data:

- **Ease of use**: You can write small, concise and intutive mathematical expressions like `(kanto * weights).sum()` rather than using loops & custom functions like `crop_yeild`.
- **Performance**: Numpy operations and functions are implemented internally in C++, which makes them much faster than using Python statements & loops which are interpreted at runtime

Here's a quick comparision of dot products done of vectors with a million elements each using Python loops vs. Numpy arrays.

In [31]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [32]:
arr1 * arr2

array([ 4, 10, 18])

In [33]:
arr2.sum()

np.int64(15)

In [34]:
arr1 = list(range(1000000))
arr2 = list(range(1000000,2000000))

arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [35]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1 * x2
print(result)

833332333333500000
CPU times: total: 531 ms
Wall time: 547 ms


In [36]:
%%time
print(np.dot(arr1_np, arr2_np))

833332333333500000
CPU times: total: 0 ns
Wall time: 3.8 ms


As you can see, using `np.dot` is 100 times faster than using a `for` loop. This makes Numpy especially useful while working with really large datasets with tens of thousands or millions of data points.

Let's save our work before continuing.

## Multi-dimensional Numpy arrays 

We can now go one step further, and represent the climate data for all the regions together using a single 2-dimensional Numpy array.

In [57]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64], 
                         [87, 134, 58],
                         [102, 43, 37], 
                         [69, 96, 70]])

In [58]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [59]:
climate_data.shape

(5, 3)

In [60]:
weights

array([0.3, 0.2, 0.5])

In [61]:
weights.shape

(3,)

Same output for below three different inputs, how `.dot()` , `.matlmul()` and `@` works

In [62]:
np.dot(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [63]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [64]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

### Example array

In [70]:
# 1D array
arr1 = np.array([[1,2,3]])
print(x)
print(x.shape)

[[1 2 3]]
(1, 3)


In [71]:
# 2D array 
arr2 = np.array([[1,2,3], 
                [4,5,6]])
print(arr2) 
print(arr2.shape) 

[[1 2 3]
 [4 5 6]]
(2, 3)


In [72]:
# 3D array
arr3 = np.array([
    [[1,2,3], 
     [4,5,6]],
    [[1,2,3], 
     [4,5,6]]
])
print(arr3) 
print(arr3.shape) 

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)


All the elements in a numpy array have the same datatype. You can check the data type of an array using the `.dtype` property

In [74]:
arr1.dtype

dtype('int64')

If an array contains even a single floating point number, all the other elements are also coverted to floats.

In [75]:
weights.dtype

dtype('float64')

## Arithmetic operations and broadcasting

Numpy arrays support arithmetic operators like `+`, `-`, `*` etc. You can perform an arithmetic operation with a single number (also called scalar), or with another array of the same shape. This makes it really easy to write mathemtical expressions with multi-dimensional arrays.

In [3]:
arr1 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [4]:
arr2 = np.array([[11,12,13,14],
                 [15,16,17,18], 
                 [19, 11, 12, 13]])

In [8]:
# Adding a scalar
print(arr2 + 5)

[[16 17 18 19]
 [20 21 22 23]
 [24 16 17 18]]


In [9]:
print(arr2 - arr1)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [10]:
# Multiplying a scalar 
print(arr1 * 2)

[[ 2  4  6  8]
 [10 12 14 16]
 [18  2  4  6]]


In [12]:
# Division by scalar 
arr2 / 2

array([[5.5, 6. , 6.5, 7. ],
       [7.5, 8. , 8.5, 9. ],
       [9.5, 5.5, 6. , 6.5]])

In [13]:
# element-wise multiplication
arr1 * arr2

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [17]:
arr1 @ arr2.T

array([[130, 170, 129],
       [330, 434, 349],
       [179, 239, 245]])

In [15]:
arr1.shape

(3, 4)

In [16]:
arr2.shape

(3, 4)

In [19]:
arr1 % 4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]])

# FOR REMAINING

Numpy arrays also support *brodcasting*, which allows arthmetic operations between two array having a different number of dimensions, but compatible shapes. Let's look at an example to see how it works.

In [3]:
arr1 = np.array([[1,2,3,4], 
                 [5,6,7,8], 
                 [9,1,2,3]])

In [4]:
arr1.shape

(3, 4)

In [5]:
arr2 = np.array([4,5,6,7])

In [6]:
arr2.shape

(4,)

In [7]:
arr1 + arr2

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

When the expression `arr1 + arr2` is evaluated, `arr2` (which has the shape `(4,)`) is replicated 3 times to match the shape `(3, 4)` of `arr1`. This is pretty useful, because numpy performs the replication without actually creating 3 copies of the smaller dimension array.

Broadcasting only works if one of the arrays can be replicated to exactly match the shape of the other array.

In [9]:
arr3 = np.array([7,8])

In [10]:
arr1 + arr3 

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

In the above example, even if `arr3` is replicated 3 times, it will not match the shape of `arr3`, hence `arr1 + arr3` cannot be evaluted successfully. Learn more about brodcasting here: https://numpy.org/doc/stable/user/basics.broadcasting.html

#### Conditional Operators with ARRAYS
Numpy arrays also support comparision operations like `==`, `!=`, `>` etc. The result is an array of booleans.

In [11]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

In [12]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [13]:
arr1 != arr2

array([[ True, False, False],
       [ True,  True, False]])

In [14]:
arr1 >= arr2

array([[False,  True,  True],
       [ True,  True,  True]])

In [15]:
arr1 <= arr2

array([[ True,  True,  True],
       [False, False,  True]])

A common use case for this is to count the number of equal elements in two arrays using the `sum` method. Remember that `True` evalues to `1` and `False` evaluates to `0` when booleans are used in arithmetic operations.

In [17]:
print((arr1 == arr2).sum())

3


## Array indexing and slicing

Numpy extends Python's list indexing notation using `[]` to multiple dimensions in a fairly intuitive fashion. You can provide a comma separated list of indices or ranges to select a specific element or a subarray (also called slice) from a numpy array.

In [18]:
arr = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [19]:
arr.shape

(3, 2, 4)

In [21]:
# Single element
arr[1,1,2]

np.float64(36.0)

In [22]:
# Subarray using ranges
arr[1:,0:1,:2]

array([[[15., 16.]],

       [[98., 32.]]])

In [23]:
# Mixing indices and ranges
arr[1:,1,3]

array([18., 43.])

In [24]:
arr[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [25]:
arr[:2,1]

array([[13., 14., 15., 19.],
       [63., 92., 36., 18.]])

## Other ways of creating Numpy arrays

Numpy also provides some handy functions to create arrays of a desired shape with fixed or random values. Check the out the [official documentation](https://numpy.org/doc/stable/reference/routines.array-creation.html) or use the `help` function to learn more about the following functions.

In [27]:
# All zeros matrix
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [28]:
# All Ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# Random vector
np.random.rand(5)

array([0.8503614 , 0.10258783, 0.77889928, 0.37643012, 0.35017176])

In [31]:
# Random Matrix
np.random.randn(2,3)

array([[-0.08032587, -0.29563113, -0.19979484],
       [-0.22570844,  0.19001834, -0.03002983]])

In [36]:
# Fixed value
np.full([3,3], 27)

array([[27, 27, 27],
       [27, 27, 27],
       [27, 27, 27]])

In [37]:
# Range with start, stop and step
np.arange(10, 90, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [38]:
# Equally spaced numbers in a range
np.linspace(3, 27, 9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [39]:
y = np.array([[[1],[2]],
              [[3],[4]]])

In [40]:
y.shape

(2, 2, 1)