## NumPy Fundamentals to Advanced

In [1]:
import numpy as np

In [2]:
# Create a NumPy array from the list:
arr = np.array([10, 20, 30, 40, 50])

In [3]:
arr.shape

(5,)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.dtype

dtype('int64')

In [6]:
arr_2d = arr.reshape(5,1)
arr_2d

array([[10],
       [20],
       [30],
       [40],
       [50]])

In [7]:
# Create the following 3×3 matrix:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [8]:
mat[1]

array([4, 5, 6])

In [9]:
mat[0:, 2]

array([3, 6, 9])

In [10]:
mat[1:, 1:]

array([[5, 6],
       [8, 9]])

In [11]:
# Arithmetic Operations & Broadcasting
a = np.array([1, 2, 3, 4])

In [12]:
a * 5

array([ 5, 10, 15, 20])

In [13]:
a + 10

array([11, 12, 13, 14])

In [16]:
a ** 2

array([ 1,  4,  9, 16])

In [15]:
a.sum()

np.int64(10)

In [24]:
# Comparison Operations
arr = np.array([12, 45, 7, 23, 90, 18])

In [25]:
print(arr[arr > 20])

[45 23 90]


In [27]:
print((arr > 20).sum())

3


In [28]:
arr[arr < 20] = 0
arr

array([ 0, 45,  0, 23, 90,  0])

In [29]:
# Dot Product & Matrix Multiplication
a = np.array([1,2,3])
b = np.array([4,5,6])

In [30]:
np.dot(a, b)

np.int64(32)

In [31]:
a @ b

np.int64(32)

In [32]:
np.matmul(a, b)

np.int64(32)

In [33]:
# Array Creation Functions

In [36]:
# A 3×3 array of zeros
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
# A 4×4 identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
# 10 equally spaced values between 0 and 1
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [46]:
# Random array of shape (2,3)
arr = np.random.rand(2, 3)

In [47]:
arr

array([[0.30826473, 0.38946044, 0.66826809],
       [0.86736643, 0.6100454 , 0.79282591]])

In [52]:
np.mean(arr)

np.float64(0.6060384996852437)

In [53]:
arr.std()

np.float64(0.20109934461649814)

In [54]:
arr.sum()

np.float64(3.636230998111462)

In [73]:
# Reshaping & Concatenation
a = np.array([1,2,3,4,5,6])

In [74]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
a.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
a = a.reshape(2, 3)

In [77]:
b = np.array([[7,8,9],[10,11,12]])

In [78]:
np.concatenate((a, b), axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [83]:
a = np.array([1,2,3,4,5,6])
a = a.reshape(3, 2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [84]:
b = b.reshape(3, 2)
b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [85]:
np.concatenate((a, b), axis = 0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [86]:
# Reading & Writing CSV Data
data = np.genfromtxt("data.csv", delimiter = ",")

In [87]:
row_sum = np.sum(data, axis = 1)

In [88]:
row_sum

array([ nan, 150., 240.])

In [89]:
np.savetxt("output.csv", row_sum, delimiter = ",")

In [90]:
data = np.genfromtxt("data.csv", delimiter=",")
row_sum = np.sum(data, axis=1)
np.savetxt("output.csv", row_sum, delimiter=",")