## NumPy Fundamentals to Advanced

In [1]:
import numpy as np

In [2]:
# Create a NumPy array from the list:
arr = np.array([10, 20, 30, 40, 50])

In [3]:
arr.shape

(5,)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.dtype

dtype('int64')

In [6]:
arr_2d = arr.reshape(5,1)
arr_2d

array([[10],
       [20],
       [30],
       [40],
       [50]])

In [7]:
# Create the following 3×3 matrix:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [8]:
mat[1]

array([4, 5, 6])

In [9]:
mat[0:, 2]

array([3, 6, 9])

In [10]:
mat[1:, 1:]

array([[5, 6],
       [8, 9]])

In [11]:
# Arithmetic Operations & Broadcasting
a = np.array([1, 2, 3, 4])

In [12]:
a * 5

array([ 5, 10, 15, 20])

In [13]:
a + 10

array([11, 12, 13, 14])

In [16]:
a ** 2

array([ 1,  4,  9, 16])

In [15]:
a.sum()

np.int64(10)

In [24]:
# Comparison Operations
arr = np.array([12, 45, 7, 23, 90, 18])

In [25]:
print(arr[arr > 20])

[45 23 90]


In [27]:
print((arr > 20).sum())

3


In [28]:
arr[arr < 20] = 0
arr

array([ 0, 45,  0, 23, 90,  0])

In [29]:
# Dot Product & Matrix Multiplication
a = np.array([1,2,3])
b = np.array([4,5,6])

In [30]:
np.dot(a, b)

np.int64(32)

In [31]:
a @ b

np.int64(32)

In [32]:
np.matmul(a, b)

np.int64(32)

In [33]:
# Array Creation Functions

In [36]:
# A 3×3 array of zeros
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
# A 4×4 identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
# 10 equally spaced values between 0 and 1
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [46]:
# Random array of shape (2,3)
arr = np.random.rand(2, 3)

In [47]:
arr

array([[0.30826473, 0.38946044, 0.66826809],
       [0.86736643, 0.6100454 , 0.79282591]])

In [52]:
np.mean(arr)

np.float64(0.6060384996852437)

In [53]:
arr.std()

np.float64(0.20109934461649814)

In [54]:
arr.sum()

np.float64(3.636230998111462)

In [73]:
# Reshaping & Concatenation
a = np.array([1,2,3,4,5,6])

In [74]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
a.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
a = a.reshape(2, 3)

In [77]:
b = np.array([[7,8,9],[10,11,12]])

In [78]:
np.concatenate((a, b), axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [83]:
a = np.array([1,2,3,4,5,6])
a = a.reshape(3, 2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [84]:
b = b.reshape(3, 2)
b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [85]:
np.concatenate((a, b), axis = 0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [86]:
# Reading & Writing CSV Data
data = np.genfromtxt("data.csv", delimiter = ",")

In [87]:
row_sum = np.sum(data, axis = 1)

In [88]:
row_sum

array([ nan, 150., 240.])

In [89]:
np.savetxt("output.csv", row_sum, delimiter = ",")

In [90]:
data = np.genfromtxt("data.csv", delimiter=",")
row_sum = np.sum(data, axis=1)
np.savetxt("output.csv", row_sum, delimiter=",")

## Important Topics

#### Broadcasting
NumPy automatically expands smaller arrays to match larger array shapes during operations.

In [1]:
import numpy as np
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])

In [2]:
print(a + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [3]:
# Add a row vector [1,2,3] to every row of a 3×3 matrix.
a = np.array([1, 2, 3])
b = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

In [4]:
print(a + b)

[[11 22 33]
 [41 52 63]
 [71 82 93]]


#### Axis Concept
`axis=0` works column-wise, `axis=1` works row-wise.

In [5]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(np.sum(arr, axis = 0))
print(np.sum(arr, axis = 1))

[5 7 9]
[ 6 15]


In [7]:
# Find row-wise mean and column-wise mean of a 3×3 matrix.
arr = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])
print(np.mean(arr, axis = 1))
print(np.mean(arr, axis = 0))

[20. 50. 80.]
[40. 50. 60.]


#### Fancy Indexing
Fancy indexing selects multiple specific elements using index lists.

In [13]:
arr = np.array([10,20,30,40])

print(arr[[0,2]])
print(arr[0:2])
# Select 2nd and 4th elements from an array.
print(arr[[1,3]])

[10 30]
[10 20]
[20 40]


#### Boolean Masking
Boolean masking filters array elements using conditions.

In [16]:
arr = np.array([5,12,18,25])
print(arr[arr > 10])
# Print numbers divisible by 2 from an array.
print(arr[arr % 2 == 0])

[12 18 25]
[12 18]


#### Flatten & Ravel
`flatten()` converts multi-dimensional arrays into 1D arrays.

In [17]:
arr = np.array([[1,2],[3,4]])

print(arr.flatten())

[1 2 3 4]


In [18]:
arr = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])
print(arr.flatten())

[10 20 30 40 50 60 70 80 90]


#### Transpose
Transpose swaps rows and columns.

In [20]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


(2, 3)

In [21]:
arr = np.array([[10, 20],
              [40, 50],
              [70, 80]])
arr.T

array([[10, 40, 70],
       [20, 50, 80]])

#### Horizontal & Vertical Stack
`hstack` joins arrays horizontally, `vstack` joins vertically.

In [22]:
a = np.array([1,2])
b = np.array([3,4])

print(np.hstack((a,b)))
print(np.vstack((a,b)))

[1 2 3 4]
[[1 2]
 [3 4]]


In [26]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(np.hstack((a, b)))
print(np.vstack((a, b)))

[ 1  2  3 10 20 30]
[[ 1  2  3]
 [10 20 30]]


#### Random Integers
`randint()` generates random integers in a range.

In [28]:
print(np.random.randint(1,10,(2,3)))

[[7 4 5]
 [3 9 2]]


In [33]:
# Generate a random 4×4 matrix between 1–50.
print(np.random.randint(1, 50,(4, 4)))

[[21 22  1 21]
 [32 32 18 28]
 [ 7 38 40 21]
 [ 2 22 10 34]]


#### Seed
* `seed()` makes random outputs reproducible.
* Generate the same random array twice using seed.

In [40]:
np.random.seed(42)
print(np.random.rand(3))
print(np.random.rand(3))
print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]
[0.59865848 0.15601864 0.15599452]
[0.05808361 0.86617615 0.60111501]


In [37]:
np.random.rand(3)

array([0.59865848, 0.15601864, 0.15599452])

In [39]:
np.random.rand(3)

array([0.05808361, 0.86617615, 0.60111501])

#### Mathematical Functions
NumPy provides fast built-in math operations.

In [41]:
arr = np.array([1,4,9])

print(np.sqrt(arr))
print(np.max(arr))

[1. 2. 3.]
9


In [43]:
# Find square root, maximum, and minimum of an array. 
arr = np.array([1, 2, 3, 4, 5])
print(np.sqrt(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
1
5
1.4142135623730951


#### Argmax & Argmin
`argmax()` gives index of largest value, `argmin()` gives index of smallest value.

In [44]:
arr = np.array([10,50,20])

print(np.argmax(arr))
print(np.argmin(arr))

1
0


#### 3D Arrays
3D arrays store data in layers, rows, and columns.

In [47]:
arr = np.array([[[1,2],
                 [3,4]],
                [[5,6],
                 [7,8]]
])

print(arr.shape)
arr[1, :1, 1]

(2, 2, 2)


array([6])